trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo K8S Terraform Azure!
  displayName: 'Run a one-line script'
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'
- task: TerraformCLI@2
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/01-currency-exchange-microservice-basic/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id=$(cliend_id) -var client_secret=$(client_secret) -var ssh_publickey=$(publci_key.secureFilePath)'
    backendType: 'azurerm'
    backendServiceArm: 'Free Trial(c52c2fa1-8351-4fab-aedc-3dda7d3272ee)'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform_backend_rg'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'hruthikstorage'
    backendAzureRmContainerName: 'hruthikstoragecontainer'
    backendAzureRmKey: 'hruthik.y@1'
    allowTelemetryCollection: true
