trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo K8S Terraform Azure!
  displayName: 'Run a one-line script'
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/01-currency-exchange-microservice-basic/configuration/iaac/azure /Kubernetes/'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    backendServiceArm: 'Azure_resource_group'
    backendAzureRmResourceGroupName: 'Azure-Terraform_rg'
    backendAzureRmStorageAccountName: 'azuretfhruthik'
    backendAzureRmContainerName: 'azure-tf-hruthik'
    backendAzureRmKey: 'azurehruthik@1'

